version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      - run: sudo snap install cmake --classic
      - run: sudo apt-get install python3.6
      - run: sudo apt-get install build-essential
      - run: sudo pip3 install conan
      - run: sudo apt install ninja-build
      - run: conan profile new default --detect
      - run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan remote add nemtech https://api.bintray.com/conan/nemtech/symbol-server-dependencies
      - run: mkdir _build
      - run: cd _build
      - run: conan install --build=missing ..
      - run:
          name: build Script
          command: |
            cmake .. -DUSE_CONAN=ON -DCATAPULT_BUILD_DEVELOPMENT=1 -GNinja
            ninja -j8
            ctest

workflows:
  main:
    jobs:
      - build-and-test
